seantan1/Auxiun-webpage

package-lock.json
package.json
src/App.js
src/components/footer-components/Footer.js
src/components/footer-components/css/Footer.css
src/components/login-components/Login.js
src/components/navbar-components/css/Navbar.css

Implemented the front end for sign in page

Implemented Sign in Page

---

src/components/navbar-components/Navbar.js

Added in login link to the '...' dropdown menu

Fixed navigation links

---

src/components/home-components/Banner.js
src/components/home-components/css/Banner.css

Added in the following
- Banner title (NFT Marketplace for Gamers and Creators)
- Banner caption (Are you a passionate gamer? Check out our Marketplace!)
- Button (Explore Marketplace)

Completed home page banner

---

src/components/navbar-components/css/Navbar.css

Changed font to a darker colour

Changed connect wallet font colour

---

src/components/navbar-components/css/Navbar.css

Font colour was previously white - not readable.
Changed to black.

Fixed '...' font color

---

.gitignore
src/components/login-components/Login.js
src/components/register-components/Register.js

1. Login and Register functions using axios querying from the database api deployed on VPS
2. requires .env file containing the private variables

Implemented Login and Register

---

src/components/navbar-components/Navbar.js

Logo previously opened a list of navigation option - the list of option can be found in the "..." menu.
Logo now redirects to the home page.

Logo now redirects to home page

---

src/components/navbar-components/css/Navbar.css

Aligned navigation links to be centered

Repositioned navbar title 

---

src/components/footer-components/Footer.js

Footer position is now closer to the bottom of the page.

Fixed footer position

---

src/App.js
src/components/login-components/Login.js
src/components/register-components/Register.js

Bringing in the alerts for register and login into the develop branch

Register2.0

---

src/components/navbar-components/Navbar.js
src/components/navbar-components/css/Navbar.css

Changed font colour to suit nav bar theme and background colour to grey when scrolling

Changed nav title font colour and background color when scrolling

---

src/App.js
src/components/login-components/Login.js
src/components/navbar-components/Navbar.js
src/components/profile-component/Profile.js
src/components/register-components/Register.js

Implementations:
1.  user data stored in session using localStorage
2. login function stores user data
3. updated register function to check for same password and confirm password
4. updated register function to post firstname and lastname to database api
5.  display session user data on profile page

User session & integration

---

src/App.js
src/components/forgotPassword-components/ForgotPassword.js
src/components/forgotPassword-components/css/ForgotPassword.css
src/components/login-components/Login.js

created forgot password page. bringing into develop

Forgot password

---

package.json
src/components/home-components/Banner.js

Added animation text in home page banner:
> const values = ["gamer", "content creator", "artist"];

home page text banner animation

---

src/components/footer-components/Footer.js
src/components/footer-components/css/Footer.css

1. Aligned subscribe button
2. Removed social media icons

Removed social media icons in footer and aligned subscribe button

---

src/components/home-components/Banner.js
src/components/home-components/css/Banner.css

1. Added animation to explore marketplace button
2. Made home page banner more responsive on mobile devices

Changed explore button and made page more responsive

---

package.json
src/components/marketplace-components/Item.js
src/components/marketplace-components/MarketPlace.js
src/components/marketplace-components/MarketplaceCarousel.js
src/components/marketplace-components/css/MarketPlace.css

Bringing in new marketplace features

Marketplace 2.0

---

src/components/home-components/Team.js
src/components/home-components/css/Team.css

Finished front end for team section. Made it more modern.

finished team section

---

src/components/home-components/Banner.js
src/components/home-components/css/Announcement.css
src/components/home-components/css/Banner.css

animation background for banner

---

src/components/home-components/Banner.js
src/components/home-components/css/Banner.css

removed animated background

---

package.json
src/App.js
src/components/home-components/About.js
src/components/home-components/Banner.js
src/components/home-components/Team.js
src/components/home-components/css/About.css
src/components/home-components/css/Announcement.css
src/components/home-components/css/Banner.css
src/components/home-components/css/Media.css
src/components/home-components/css/Roadmap.css
src/components/home-components/css/Team.css

front end adjustment to home page

---

src/App.js
src/components/createTokens-component/CreateTokens.js
src/components/navbar-components/Navbar.js
src/components/navbar-components/css/Navbar.css
src/components/navbar-components/css/WalletProviderWindow.css
src/contract-data/rpc-data.js

1. Fixed image upload for creating nftMetadata instance on database
2. Implemented network switch for metamask wallet connection

Metamask & nft upgrade

---

src/components/buy-components/Buy.js
src/components/marketplace-components/Item.js
src/components/marketplace-components/MarketPlace.js

1. Implemented popularity in database
2. Trending carousel displays popularity number in descending order

implement popularity

---

src/App.js
src/components/buy-components/Buy.js
src/components/inventory-components/Item.js
src/components/navbar-components/Navbar.js
src/components/watch-components/Item.js
src/components/watch-components/Watch.js
src/components/watch-components/css/Watch.css

1. Adding watchlist item
2. Personal watchlist page for users
3. Deleting watchlist item

Watch page

---

package.json
src/App.css
src/components/home-components/About.js
src/components/home-components/Announcement.js
src/components/home-components/Media.js
src/components/home-components/Roadmap.js
src/components/home-components/Team.js

Implemented AOS scrolling animation for home page
- https://www.npmjs.com/package/aos

Added AOS scrolling animation for home page

---

.gitignore
package.json
src/App.js
src/components/login-components/Login.js
src/components/register-components/Register.js
src/index.js

Added an apikey to headers of all requests.
(Used an interceptor - see index.js)

Apikey header

---

src/components/createTokens-component/CreateTokens.js

Admins can now add new wallets to the admin list

Add admin feature
